### ISSUE TITLE
fromBuffer()?

### ISSUE THREAD

**Issue by drazisil** [francisrstokes/construct-js#4]
First, this looks amazing and is just what I need to keep my binary structs sane!

Is there a `fromBuffer()? If I receive one of these in Buffer form, is there a way to load it into a Struct? I see a few get methods, but not any set ones.

**Comment by francisrstokes** [comment]
Hi - apologies for getting back late on this

So construct is only creating the structures, not parsing them. This is because more complex structures often have variable length section which have to be parsed contextually and this is a bit outside the scope of this lib.
That said, you can write contextual binary parsers with a library called [arcsecond](https://github.com/francisrstokes/arcsecond) in conjunction with the extra parsers in [arcsecond-binary](https://github.com/francisrstokes/arcsecond-binary).
